<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>elGuille.gsMsg2WndLib</RootNamespace>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Description>Biblioteca de clases para enviar mensajes a ventanas de Windows compilada para .NET 9.0.
Revisión del 05-oct-2026</Description>
    <Version>6.0.0</Version>
      <FileVersion>6.0.0.0</FileVersion>
    <PackageReleaseNotes>v6.0.0.0 05-oct-2026 Versión para .NET 9.0
v5.0.0.0 07-jun-2021 Versión para .NET 5.0
Revisiones anteriores para .NET Framework 4.8:
15/Sep/2020 - 18/Mar/2019 - 21/Abr/2006 - 08/Feb/2004
v4.0.0.3 15-sep-2020</PackageReleaseNotes>
    <Authors>elGuille</Authors>
    <Copyright>©Guillermo Som (elGuille), 2002-2006, 2019-2021, 2026</Copyright>
      <OptionStrict>On</OptionStrict>
      <OptionInfer>On</OptionInfer>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
